### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by hasirk** [blackholeLFL/The-WRF-dataset#1]
Thank you for the interesting papers and corresponding datasets. Is there a direct download link to download datasets ?

**Comment by yangtzech** [comment]
It's mentioned in the README: 

> BaiduYun link: https://pan.baidu.com/s/1lW45jcXt1thpY-IVK-gZ1Q?pwd=7vaw

It's a cloud drive popularly used in China. You can search with `Baidu Netdisk` about registering and using.

If you don't know how to use it, you may email the paper's corresponding author, asking for uploading to GitHub directly.

> https://link.springer.com/article/10.1007/s10044-022-01059-2

**Comment by hasirk** [comment]
I could download it. Thanks :)
